### ISSUE TITLE
Hi! Amazing Work!

### ISSUE THREAD

**Issue by gilzellner** [Nautili/ArduboyTetris#1]
I just got my Arduboy today and yours is the first game I tried, really cool.
Are you intending to add modern tetris features like Upcoming piece and hold ?

**Comment by Nautili** [comment]
Glad you like it! I wasn't planning on doing anything else with it, but I can add a few features when I get some time (soon). I'll probably add upcoming piece and implement a half baked idea I've been wanting to try. Anything else is low priority for me and mostly just polish.

**Comment by gilzellner** [comment]
Amazing that you can do this in your free time, since my kid was born I haven't done any home coding projects :(, did build a home arcade machine though (https://heathenasparagus.wordpress.com/2016/10/03/home-built-arcade-machine/)
I would do it myself but last time I touched C++ was in College in 2009, been doing mostly Python and Ruby since.
As for features:
I would go for "hold" (replace one of the rotate buttons), ghost of the piece on where it will fall, and a piece queue. (see Tetris the grand master 3, which is the de facto standard for competitive Tetris: https://www.youtube.com/watch?v=-_b6H8dHHm0).

Anyway, thanks for making an awesome game! you rock!
