### ISSUE TITLE
trying to add "hold" feature, could use your assistance

### ISSUE THREAD

**Issue by gilzellner** [Nautili/ArduboyTetris#4]
Hi!
I am trying to add a hold feature:
https://github.com/gilzellner/ArduboyTetris/tree/hold_feature

not quite sure how to do the graphics for that
Any chance you can add the display of the held piece so I can debug this?

thanks!

(no biggie if you don't feel like it, we all have jobs and stuff)

**Comment by Nautili** [comment]
I think drawNextPiece should work. It takes a reference to a piece and an (x, y) location and draws the piece there. If you are using it to also show the held piece, drawNextPiece should probably be renamed to drawPieceAt. Let me know if that does not work.

**Comment by gilzellner** [comment]
works, thanks!
