### ISSUE TITLE
your code is much more polished than mine

### ISSUE THREAD

**Issue by gilzellner** [Nautili/ArduboyTetris#6]
I'm still happy I got it working even though almost none of my code is left in the build

**Comment by Nautili** [comment]
Thanks. It definitely helped to have what you wrote to work with.

**Comment by gilzellner** [comment]
Next features: 
Ghost piece (show the piece on the bottom as ghost)
Double points for back 2 back tetris.

**Comment by gilzellner** [comment]
Ghost piece: http://tetris.wikia.com/wiki/Ghost_piece
Back2Back: https://harddrop.com/wiki/Back-to-Back

**Comment by gilzellner** [comment]
Question:
Where did you take scoring from?

**Comment by Nautili** [comment]
I think the [original](http://tetris.wikia.com/wiki/Scoring). Looking at my code, I might have started from level 1 instead of 0, but it should be effectively the same.
